services:
  - type: web
    name: hue-house-amazon-review
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT web_app.app:app
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: REVIEW_APP_PASSWORD
        sync: false
      - key: REVIEW_APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
